from arches.trans_unet import TransUnet
#from arches.trans_unet_h8 import TransUnet_h8
#from arches.trans_unet_p32 import TransUnet_p32
#from arches.trans_unet_h8_p32 import TransUnet_h8_p32
from arches.unet import Unet
from arches.unext import Unext
from arches.multires import MultiResUnet
from arches.unetpp import UnetPP
from arches.unet_gpt import GPTNet
