arch: UNext
batch_size: 6
cfg: null
dataset: isic_2018
deep_supervision: false
early_stopping: 10
epochs: 400
factor: 0.1
gamma: 0.6666666666666666
img_ext: .jpg
input_channels: 3
input_h: 256
input_w: 256
loss: BCEDiceLoss
lr: 0.0001
mask_ext: .png
milestones: 1,2
min_lr: 1.0e-05
momentum: 0.9
name: isic_0
nesterov: false
num_classes: 1
num_workers: 4
optimizer: Adam
patience: 2
scheduler: CosineAnnealingLR
weight_decay: 0.0001
